### ISSUE TITLE
Support for the experimental syntax 'importAttributes' isn't currently enabled (1:28)

### ISSUE THREAD

**Issue by eisenheim94** [lifinance/widget#202]
<img width="1201" alt="image" src="https://github.com/lifinance/widget/assets/2355948/7491d008-8eb5-4ab6-b6c0-70503fff0d40">

Hi! Looks like you have experimental / new features of TS that not compatible with previous versions.
I even updated TS to 5.3.3 and it didn't helped with this, so I'm working with my CRA setup to enable it with `customize-cra` in Babel config.

**Comment by chybisov** [comment]
@eisenheim94 hey, sorry for the long response, it took a while to finish the next release. Please try the latest alpha, it should be fixed 🙂 

It also includes some breaking changes, which will be documented in the updated documentation later in April, but if you have any questions about the customization, please let me know 🙂 Thank you!

**Comment by DNR500** [comment]
We have since updated import asserts in Widget so that there should be less problems with them in other projects. 

Note that CRA is now considered to be deprecated, however we still have a example that allows a CRA project still to work with import assertions. Take a look a the configuration in 

https://github.com/lifinance/widget/tree/main/examples/create-react-app

**Comment by webdott** [comment]
Hey @DNR500 

I see that the example has been removed. Any other workaround for this? Thanks

**Comment by chybisov** [comment]
@webdott please migrate to Vite.
